package gov.cms.madie.terminology.service;

import generated.vsac.nlm.nih.gov.RetrieveMultipleValueSetsResponse;
import gov.cms.madie.models.cql.terminology.CqlCode;
import gov.cms.madie.models.cql.terminology.VsacCode;
import gov.cms.madie.terminology.dto.Code;
import gov.cms.madie.terminology.dto.CodeStatus;
import gov.cms.madie.terminology.dto.ValueSetsSearchCriteria;
import gov.cms.madie.terminology.exceptions.VsacUnauthorizedException;
import gov.cms.madie.terminology.mapper.VsacToFhirValueSetMapper;
import gov.cms.madie.terminology.models.CodeSystem;
import gov.cms.madie.terminology.models.UmlsUser;
import gov.cms.madie.terminology.repositories.CodeSystemRepository;
import gov.cms.madie.terminology.repositories.UmlsUserRepository;
import gov.cms.madie.terminology.util.TerminologyServiceUtil;
import gov.cms.madie.terminology.webclient.TerminologyServiceWebClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.hl7.fhir.r4.model.ValueSet;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;

import static gov.cms.madie.terminology.util.TerminologyServiceUtil.sanitizeInput;

@Service
@Slf4j
@RequiredArgsConstructor
public class VsacService {

  private final TerminologyServiceWebClient terminologyWebClient;
  private final VsacToFhirValueSetMapper vsacToFhirValueSetMapper;
  private final CodeSystemRepository codeSystemRepository;
  private final UmlsUserRepository umlsUserRepository;
  private static final String CS_VERSION_PREFIX = "urn:hl7:version:";

  /**
   * If umlsUser is not available or if API-KEY is unavailable then return false. Otherwise, return
   * true.
   *
   * @param userName harpId
   * @return true/false based on if user's API-KEY is available in the data store.
   */
  public boolean validateUmlsInformation(String userName) {
    Optional<UmlsUser> umlsUser = findByHarpId(userName);
    return umlsUser.isPresent() && !StringUtils.isBlank(umlsUser.get().getApiKey());
  }

  public RetrieveMultipleValueSetsResponse getValueSet(
      String oid,
      UmlsUser umlsUser,
      String profile,
      String includeDraft,
      String release,
      String version) {
    log.debug("Fetching SVS ValueSet: " + oid);
    return terminologyWebClient.getValueSet(
        oid, umlsUser.getApiKey(), profile, includeDraft, release, version);
  }

  public ValueSet convertToFHIRValueSet(RetrieveMultipleValueSetsResponse vsacValueSetResponse) {
    return vsacToFhirValueSetMapper.convertToFHIRValueSet(vsacValueSetResponse);
  }

  public List<RetrieveMultipleValueSetsResponse> getValueSets(
      ValueSetsSearchCriteria searchCriteria, UmlsUser umlsUser) {
    List<ValueSetsSearchCriteria.ValueSetParams> valueSetParams =
        searchCriteria.getValueSetParams();
    return valueSetParams.stream()
        .map(
            vsParam ->
                getValueSet(
                    vsParam.getOid(),
                    umlsUser,
                    searchCriteria.getProfile(),
                    searchCriteria.getIncludeDraft(),
                    vsParam.getRelease(),
                    vsParam.getVersion()))
        .collect(Collectors.toList());
  }

  /**
   * @param cqlCodes List of objects generated by Antlr from user entered CQL string.
   * @param umlsUser umls information from db
   * @return List of CqlCodes with their validation results. If an associated CodeSystem is not
   *     available for a code, then this method will skip validating that code, an error will be
   *     displayed to user by cql-elm-translator
   */
  public List<CqlCode> validateCodes(List<CqlCode> cqlCodes, UmlsUser umlsUser, String model) {
    cqlCodes.forEach(cqlCode -> validateCode(cqlCode, umlsUser, model));
    return cqlCodes;
  }

  private void validateCode(CqlCode cqlCode, UmlsUser umlsUser, String model) {
    cqlCode.setValid(true);

    // Verify Code is provided.
    if (sanitizeInput(cqlCode.getCodeId()).isBlank()) {
      log.info("Code Id is not available for code {}", cqlCode.getName());
      cqlCode.setValid(false);
      cqlCode.setErrorMessage("Code Id is required");
      return;
    }

    // Verify Code System info is provided.
    if (cqlCode.getCodeSystem() == null) {
      return;
    }

    // Verify oid/url is provided in cql, else the code system is considered invalid.
    String cqlCodeSystemOid = sanitizeInput(cqlCode.getCodeSystem().getOid());
    if (StringUtils.isBlank(cqlCodeSystemOid)) {
      log.info("CodeSystem {} does not contain any OID/URL", cqlCode.getCodeSystem().getName());
      cqlCode.getCodeSystem().setValid(false);
      cqlCode.getCodeSystem().setErrorMessage("Code system URL is required");
      return;
    }

    List<CodeSystem> targetCodeSystemVersions;
    // Verify code system is known.
    if (model.contains("QDM")) {
      targetCodeSystemVersions = codeSystemRepository.findAllByOid(cqlCodeSystemOid);
    } else {
      targetCodeSystemVersions = codeSystemRepository.findAllByFullUrl(cqlCodeSystemOid);
    }
    if (CollectionUtils.isEmpty(targetCodeSystemVersions)) {
      log.info("No Code system versions found for {}", cqlCode.getCodeSystem().getOid());
      cqlCode.getCodeSystem().setValid(false);
      cqlCode.getCodeSystem().setErrorMessage("Unable to find a code system version");
      return;
    }

    // if all code system versions are listed as NOT IN VSAC, then it is a valid FHIR code system.
    cqlCode.getCodeSystem().setValid(true);
    if (targetCodeSystemVersions.stream()
        .map(CodeSystem::getOid)
        .allMatch(oid -> oid.contains("NOT.IN.VSAC"))) {
      return;
    }

    remoteValidateCode(umlsUser, cqlCode, targetCodeSystemVersions);
  }

  private void remoteValidateCode(
      UmlsUser umlsUser, CqlCode cqlCode, List<CodeSystem> codeSystems) {
    String codeSystemVersion = buildCodeSystemVersion(cqlCode, codeSystems);
    if (StringUtils.isBlank(codeSystemVersion)) {
      return;
    }
    String codePath =
        TerminologyServiceUtil.buildCodePath(
            codeSystems.get(0).getName(), codeSystemVersion, sanitizeInput(cqlCode.getCodeId()));
    VsacCode vsacCode = validateCodeAgainstVsac(codePath, umlsUser);
    // Invalid: If the statusCode is "error" and either CodeSystem or CodeSystem version
    // or Code is not found.
    // Valid: If the statusCode is "ok".
    if (!vsacCode.getStatus().equalsIgnoreCase("ok")) {
      buildVsacErrorMessage(cqlCode, vsacCode);
    } else {
      cqlCode.setValid(true);
    }
  }

  public CodeStatus getCodeStatus(Code code, String apiKey) {
    if (code.getSvsVersion() == null) {
      return CodeStatus.NA;
    }
    // prepare code path e.g. CODE:/CodeSystem/ActCode/Version/9.0.0/Code/AMB/Info
    String codePath =
        TerminologyServiceUtil.buildCodePath(
            code.getCodeSystem(), code.getSvsVersion(), code.getName());
    VsacCode svsCode = terminologyWebClient.getCode(codePath, apiKey);
    if (svsCode.getStatus().equalsIgnoreCase("ok")) {
      if ("Yes".equals(svsCode.getData().getResultSet().get(0).getActive())) {
        return CodeStatus.ACTIVE;
      } else {
        return CodeStatus.INACTIVE;
      }
    }
    return CodeStatus.NA;
  }

  /**
   * Verify if the user with given harp id has valid UMLS user
   *
   * @param harpId
   * @return Instance of UmlsUser
   */
  public UmlsUser verifyUmlsAccess(String harpId) {
    UmlsUser user = findByHarpId(harpId).orElse(null);
    if (user == null || StringUtils.isBlank(user.getApiKey())) {
      log.error("UMLS API Key Not found for user : [{}}]", harpId);
      throw new VsacUnauthorizedException("Please login to UMLS before proceeding");
    }
    return user;
  }

  private VsacCode validateCodeAgainstVsac(String codePath, UmlsUser umlsUser) {
    log.info("codedPath is {}", codePath);
    return terminologyWebClient.getCode(codePath, umlsUser.getApiKey());
  }

  /**
   * @param cqlCode object generated by Antlr from user entered CQL string.
   * @param codeSystems list of code systems with the same oid/url as the cqlCode's code system.
   * @return if user provides a FHIR Code system version, finds the equivalent VSAC version and
   *     returns it. If there is no equivalent version, or there are no versions at all, then this
   *     method returns user provided FHIR version. Finally, if user doesn't provide a version in
   *     CQL, get the latest vsac version from codeSystemEntry (first element in the version List).
   */
  private String buildCodeSystemVersion(CqlCode cqlCode, List<CodeSystem> codeSystems) {
    // Default to latest VSAC version if none provided.
    if (StringUtils.isBlank(cqlCode.getCodeSystem().getVersion())) {
      Optional<CodeSystem> latestCodeSystemVersion =
          codeSystems.stream().filter(CodeSystem::isLatestVersion).findFirst();
      if (latestCodeSystemVersion.isPresent()
          && StringUtils.isNotBlank(latestCodeSystemVersion.get().getVersion().getVsacVersion())) {
        return latestCodeSystemVersion.get().getVersion().getVsacVersion();
      } else {
        cqlCode.getCodeSystem().setValid(false);
        cqlCode.getCodeSystem().setErrorMessage("Unable to find a code system version");
        return "";
      }
    }

    // Locate the code system version that matches with user provided FHIR version
    // and return the equivalent VSAC version.
    String cqlCodeSystemVersion =
        sanitizeInput(cqlCode.getCodeSystem().getVersion().replace(CS_VERSION_PREFIX, ""));

    Optional<CodeSystem.Version> csVersion =
        codeSystems.stream()
            .map(CodeSystem::getVersion)
            .filter(Objects::nonNull)
            .filter(version -> version.getFhirVersion().equalsIgnoreCase(cqlCodeSystemVersion))
            .findFirst();
    if (csVersion.isPresent()) {
      return csVersion.get().getVsacVersion().isBlank()
          ? cqlCodeSystemVersion
          : csVersion.get().getVsacVersion();
    }
    log.debug(
        "None of the known FHIR code system versions {} matches with version {}",
        cqlCode.getCodeSystem().getOid(),
        cqlCodeSystemVersion);
    return cqlCodeSystemVersion;
  }

  /**
   * @param cqlCode input cqlCode
   * @param vsacCode response from vsac builds error message based on errorCode from VSAC. errorCode
   *     800 indicates CodeSystem not found. errorCode 801 indicates CodeSystem Version not found.
   *     errorCode 802 indicates Code not found.
   */
  private void buildVsacErrorMessage(CqlCode cqlCode, VsacCode vsacCode) {
    // Validation errors appear in an Errors object
    if (vsacCode.getErrors() != null
        && StringUtils.isNumeric(vsacCode.getErrors().getResultSet().get(0).getErrCode())) {
      int errorCode = Integer.parseInt(vsacCode.getErrors().getResultSet().get(0).getErrCode());
      if (errorCode == 800 || errorCode == 801) {
        log.info(
            "Error code is 800, or 801 from VSAC. Error: {}",
            vsacCode.getErrors().getResultSet().get(0));
        cqlCode.getCodeSystem().setValid(false);
        cqlCode
            .getCodeSystem()
            .setErrorMessage(vsacCode.getErrors().getResultSet().get(0).getErrDesc());
      } else if (errorCode == 802) {
        log.info(
            "Error code is 802 from VSAC. Error: {}", vsacCode.getErrors().getResultSet().get(0));
        cqlCode.setValid(false);
        cqlCode.setErrorMessage(vsacCode.getErrors().getResultSet().get(0).getErrDesc());
      }
      // API Errors appear in the status field.
    } else if (StringUtils.isNumeric(vsacCode.getStatus())) {
      cqlCode.setValid(false);
      cqlCode.setErrorMessage(
          "Communication Error with VSAC. Please retry your request. "
              + "If this error persists, please contact the Help Desk.");
    } else {
      cqlCode.setValid(false);
      log.info(
          "Error code is uncaught. General catch, Error: {} status: {}",
          vsacCode.getErrors().getResultSet().get(0),
          vsacCode.getStatus());
    }
  }

  public UmlsUser saveUmlsUser(String harpId, String apiKey) {
    Instant now = Instant.now();
    UmlsUser umlsUser =
        UmlsUser.builder().apiKey(apiKey).harpId(harpId).createdAt(now).modifiedAt(now).build();
    return umlsUserRepository.save(umlsUser);
  }

  public Optional<UmlsUser> findByHarpId(String harpId) {
    return umlsUserRepository.findByHarpId(harpId);
  }

  public boolean logoutUMLSUser(String userName) {
    Optional<UmlsUser> deletedUser = umlsUserRepository.deleteByHarpId(userName);
    boolean deleted = deletedUser.isPresent();
    if (deleted) {
      log.info("Successfully deleted UMLS information for User Name: {}", userName);
    } else {
      log.error("Error while deleting UMLS information for User Name: {}", userName);
    }
    return deleted;
  }
}
